from Bio.PDB import PDBParser
from collections import defaultdict
from pathlib import Path
import math
import sys
import osprey
import csv


def minimize(inpath, args):
    nSteps = 100 # Number of minimization steps to perform
    outpath = inpath.with_stem(inpath.stem + f'_steps{nSteps}')
    if not checkfile(outpath):
        print(f'Running sander on {inpath}. Output path: {outpath}.')

        model = PDBParser().get_structure("X", inpath)[0]
        chainListDesign = [model[chainid] for chainid in args.cld]
        chainListBinder = [model[chainid] for chainid in args.clb]

        osprey.start(heapSizeMiB=args.heapSize)
        mol = osprey.readPdb(inpath)
        ffparams = osprey.ForcefieldParams()
        templateLib = osprey.TemplateLibrary(ffparams.forcefld)


        mutableSetInfos = confTools.findConfSpacesSet(inpath, mol, templateLib,
                model, chainListDesign, chainListBinder, [], args.cutoffWM,
                args.cutoffN, [], [], 1, {}, False, False)

        fixedContents1 = \
"""Minimizing input structure to resolve clashes, generated by prepComplex.py
&cntrl
 imin=1,
 maxcyc="""
        fixedContents2 = """,
 ntpr=1,
 ntwx=10,
 ntxo=1,
 ntr=1,
 ioutfm=0,
 igb=1,
 restraint_wt=5.0,
 restraintmask="""

        restraintMask = findClashesAndMask(inpath, model, mutableSetInfos)
        allContents = fixedContents1 + str(nSteps) + fixedContents2 + f'"{restraintMask}"\n/\n'
        sanderControlPath = Path('sanderControl.mdin')
        with sanderControlPath.open(mode='w') as sanderControl:
            sanderControl.write(allContents)

        tleapInPath = Path('tleap.in')
        prmtop = inpath.with_suffix('.prmtop')
        inpcrd = inpath.with_suffix('.inpcrd')
        with tleapInPath.open(mode='w') as tleapIn:
            tleapIn.write('source leaprc.protein.ff14SB\n')
            tleapIn.write(f'mol = loadpdb {str(inpath)}\n')
            tleapIn.write('check mol\n')
            tleapIn.write(f'saveamberparm mol {str(prmtop)} {str(inpcrd)}\n')
            tleapIn.write(f'quit\n')

        tleapOutPath = Path('tleap.out')
        with tleapOutPath.open(mode='x') as tleapOut:
            subprocess.run(['tleap', '-f', str(tleapInPath)], stdout = tleapOut)
            
            
        temp_str = [
            'sander', '-O',
            '-i', str(sanderControlPath),
            '-o', 'sanderOutput.mdout',
            '-p', str(prmtop),
            '-c', str(inpcrd),
            '-ref', str(inpcrd),
            '-x', 'coords.mdcrd'
            ]
            

        subprocess.run(temp_str)

        with outpath.open(mode='x') as minimized:
            subprocess.run(['ambpdb', '-p', str(prmtop), '-c', 'restrt'], stdout = minimized)

    return outpath